### ISSUE TITLE
Insert Statements

### ISSUE THREAD

**Issue by NathanBarber97** [cst-btech-group-a/Quizzular#1]
Why?
We need insert statements to allow a user to add a quiz to the database, as well as for each component of a quiz.

Requirements:
Text file containing MySQL statements that do the following:
    -Insert quiz
    -Insert results for quizzes
    -Insert question for quizzes
    -Insert answers for questions

**Comment by nick-corcoran** [comment]
----insert a quiz-------
INSERT INTO quiz (Quiz_name) VALUES(**VARIABLE**);

----insert a question for a quiz--------
INSERT INTO questions (Quiz_id,Question_text) VALUES(**VARIABLE**,**VARIABLE**);

----insert a answer for a quiz---------
INSERT INTO answers(Questions_ID,Answer_text) VALUES(**VARIABLE**,**VARIABLE**);

-----insert results for a quiz------
INSERT INTO results(Quiz_id,Result_text,upperbound,lowerbound) VALUES(**VARIABLE**,**VARIABLE**,**VARIABLE**,**VARIABLE**);
