### ISSUE TITLE
Delete Statements

### ISSUE THREAD

**Issue by NathanBarber97** [cst-btech-group-a/Quizzular#2]
Why?
We need statements for if a user wants to delete a quiz or any of it's components.

Requirements:
Text file with working statements to do the following:
    -Delete a quiz and all its connected rows
    -Delete a question and it's answers
    -Delete an answer from a question
    -Delete a result from a quiz

**Comment by nick-corcoran** [comment]
--- delete---------
DELETE * FROM Answers WHERE EXISTS(SELECT*FROM questions WHERE ID = **VARIABLE** AND Quiz_id = **VARIABLE**)

-------delete a quiz-----
DELETE * FROM quiz 	WHERE ID = **VARIABLE**;


------delete a question-------
DELETE * FROM question WHERE Quiz_id = **VARIABLE**;


----delete results------
DELETE * FROM results WHERE Quiz_id = **VARIABLE**

**Comment by nick-corcoran** [comment]
DELETE  FROM quiz WHERE ID = **VARIABLE**;
DELETE  FROM questions WHERE Quiz_id = **VARIABLE**;
DELETE quiz, questions, answers FROM quiz INNER JOIN questions INNER JOIN answers ON quiz.id = question.Quiz_ID && questions.id = answers.question_ID WHERE quiz.id= **VARIABLE**;
DELETE  FROM results WHERE Quiz_id = **VARIABLE**; 
DELETE  FROM Answers WHERE question_id IN (SELECT question_id FROM questions WHERE Quiz_ID = VARIABLE);
