### ISSUE TITLE
Update Statements

### ISSUE THREAD

**Issue by NathanBarber97** [cst-btech-group-a/Quizzular#3]
Why?
We need statements for if a user wants to change a quiz or any of it's components.

Requirements:
Text file with working statements to do the following:
    -Change quiz information
    -Change question text
    -Change answers for questions
    -Change results text/scores for quiz

**Comment by nick-corcoran** [comment]
UPDATE quiz SET Quiz_name = **VARIABLE** WHERE ID = **VARIABLE**;

UPDATE questions SET Question_text = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE questions SET Question_text = **VARIABLE** WHERE Quiz_ID = **VARIABLE**;
UPDATE questions SET Question_text = **VARIABLE** WHERE Quiz_ID = **VARIABLE** && ID = **VARIABLE**;

UPDATE answers SET Answer_text = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE answers SET Answer_text = **VARIABLE** WHERE Questions_ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE Questions_ID = **VARIABLE**;
UPDATE answers SET Answer_text = **VARIABLE** WHERE Questions_ID = **VARIABLE** && ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE Questions_ID = **VARIABLE** && ID = **VARIABLE**;

UPDATE results SET Result_text = *VARIABLE** WHERE ID = **VARIABLE**;
UPDATE results SET Result_text = *VARIABLE** WHERE Quiz_ID = **VARIABLE**;
UPDATE results SET Result_text = *VARIABLE** WHERE Quiz_ID = **VARIABLE** && ID = **VARIABLE**;

**Comment by nick-corcoran** [comment]
UPDATE quiz SET Quiz_name = **VARIABLE** WHERE ID = **VARIABLE**;

UPDATE questions SET Question_text = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE questions SET Question_text = **VARIABLE** WHERE Quiz_ID = **VARIABLE**;
UPDATE questions SET Question_text = **VARIABLE** WHERE Quiz_ID = **VARIABLE** && ID = **VARIABLE**;

UPDATE answers SET Answer_text = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE ID = **VARIABLE**;
UPDATE answers SET Answer_text = **VARIABLE** WHERE Questions_ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE Questions_ID = **VARIABLE**;
UPDATE answers SET Answer_text = **VARIABLE** WHERE Questions_ID = **VARIABLE** && ID = **VARIABLE**;
UPDATE answers SET Answer_chosen = **VARIABLE** WHERE Questions_ID = **VARIABLE** && ID = **VARIABLE**;

UPDATE results SET Result_text = *VARIABLE** WHERE ID = **VARIABLE**;
UPDATE results SET Result_text = *VARIABLE** WHERE Quiz_ID = **VARIABLE**;
UPDATE results SET Result_text = *VARIABLE** WHERE Quiz_ID = **VARIABLE** && ID = **VARIABLE**;
