### ISSUE TITLE
Select Statements

### ISSUE THREAD

**Issue by NathanBarber97** [cst-btech-group-a/Quizzular#4]
Why?
We need statements to get a quiz or any of it's components so that it can be displayed to quiz-takers.

Requirements:
Text file with working statements to do the following:
    -Select quiz
    -Select questions for a quiz
    -Select answers for questions
    -Select results for quiz
    -Select result for quiz and score

**Comment by nick-corcoran** [comment]
----Selceting a Quiz-----
Select Quiz_name Where ID = **VARIABLE**;

---Selecting a question from a quiz----
Select * FROM questions where Quiz_id = **VARIABLE**

---Selecting a answer for a question------
SELECT Answer_text FROM answers WHERE Question_ID = **VARIABLE** && ID = **VARIABLE**;

----Selecting results for a quiz-----
SELECT * FROM results WHERE Quiz_id = **VARIABLE**;

**Comment by nick-corcoran** [comment]
----Selceting a Quiz-----
Select Quiz_name Where ID = **VARIABLE**;

---Selecting a question from a quiz----
Select * FROM questions where Quiz_id = **VARIABLE**;

---Selecting a answer for a question------
SELECT Answer_text FROM answers WHERE Question_ID = **VARIABLE**;

----Selecting results for a quiz-----
SELECT * FROM results WHERE Quiz_id = **VARIABLE** && upperbound=> **VARIABLE** && lowerbound<=**VARAIBLE**;
